name: mcs
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py37_0
  - asn1crypto=0.24.0=py37_0
  - astor=0.7.1=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1
  - cryptography=2.6.1=py37h7a1dbc1_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - gast=0.2.2=py37_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.9.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.8=py37_0
  - intel-openmp=2019.3=203
  - keras-applications=1.0.7=py_0
  - keras-preprocessing=1.0.9=py_0
  - libprotobuf=3.7.1=h7bd577a_0
  - markdown=3.1=py37_0
  - mkl=2019.3=203
  - mkl_fft=1.0.12=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - mock=2.0.0=py37_0
  - numpy-base=1.16.3=py37hc3f5095_0
  - openssl=1.1.1b=he774522_1
  - pbr=5.1.3=py_0
  - pip=19.1=py37_0
  - protobuf=3.7.1=py37h33f27b4_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyreadline=2.1=py37_1
  - pysocks=1.6.8=py37_0
  - python=3.7.3=h8c8aaf0_1
  - requests=2.21.0=py37_0
  - selenium=3.141.0=py37he774522_0
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=he774522_0
  - tensorboard=1.13.1=py37h33f27b4_0
  - tensorflow=1.13.1=gpu_py37h83e5d6a_0
  - tensorflow-base=1.13.1=gpu_py37h871c8ca_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - urllib3=1.24.2=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_4
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - zlib=1.2.11=h62dcd97_3
  - pip:
    - keras==2.2.4
    - numpy==1.16.3
    - pyyaml==5.1
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - six==1.12.0
    - textgenrnn==1.5.0
    - tqdm==4.31.1
prefix: C:\ProgramData\Miniconda3\envs\mcs

